### ISSUE TITLE
Ressources Users

### ISSUE THREAD

**Issue by Chabelle78** [WildCodeSchool/btz-0321-aeviso-client#4]

**Comment by MatthiasWanner** [comment]
- [x]  create api routes CRUD on user
  - [x] get all
  - [x] get one
  - [x] update one
  - [x] delete one
  - [x] create one

- [x]  create api routes CRUD on profession:
  - [x] get all
  - [x] get one
  - [x] update one
  - [x] delete one
  - [x] create one

- [x] create Prisma model
- [x] create some pages to handle this resource and form
