### ISSUE TITLE
Create companies ressources

### ISSUE THREAD

**Issue by Chabelle78** [WildCodeSchool/btz-0321-aeviso-client#5]

**Comment by MatthiasWanner** [comment]
- [x]  create api routes CRUD on organization
    - [x]     get all
    - [x]     get one
    - [x]     update one
    - [x]     delete one
    - [ ]     create one

 

- [ ] create api routes CRUD on status
    - [ ]     get all
    - [ ]     get one
    - [ ]     update one
    - [ ]     delete one
    - [ ]     create one

- [x] create Prisma model
- [x] create some pages to handle this resource and form
